Project cactus {
  database_type: 'PostgreSQL'
  Note: 'the database structure of the project cactus'
}

Table presentation {
  id int [pk]

  Note: 'the professors presentation table'
}

Table session {
  uuid string [pk]

  Note: 'the session table'
}