Project cactus {
  database_type: 'PostgreSQL'
  Note: 'the database structure of the project cactus'
}

Table presentation {
  id int [pk]

  Note: 'the professors presentation table'
}

Table slide {
  id int
  presentation_id int [ref: > presentation.id]

  name string

  indexs {
    (id, presentation_id) [pk]
  }
  Note: 'the slides table, which contains the slides of the presentation'
}

Table element {
  id int [pk]
  slide_id int [ref: > slide.id]

  name string
  type string
  content json

  Note: 'the elements table, which contains the elements of the presentation'

}

Table session {
  uuid string [pk]

  Note: 'the session table, which contains the session uuid, it virtualizes the classroom'
}